name: Version or Publish

on:
  push:
    branches:
      - main

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Changesets
        uses: changesets/action@v1
        with:
          # We provide a dummy publish script so that changesets will create the
          # GitHub release and the Git tags for us but not publish the npm
          # package. We still manually perform the publish using 2FA
          publish: echo Skip publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
