name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          # cache: npm # Cache service is returning 500 atm
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm pack
      - name: Upload npm package
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: publish-gh-release-package-*.tgz
