name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    uses: andrewiggins/publish-gh-release-package/.github/workflows/build.yml@main

  version:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'andrewiggins/publish-gh-release-package' # Don't run on forks
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all tags

      - uses: actions/download-artifact@v2
        with:
          name: npm-package

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      # changsets/action requires @changesets/cli to be installed. Would be nice
      # if we could install just @changesets/cli and not the entire repo's
      # dependencies
      - run: npm ci

      - id: changesets
        uses: changesets/action@v1
        with:
          publish: npx @changesets/cli tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./scripts/release/upload-gh-asset.cjs')
            return await script({ require, github, context, glob, packages: ${{ steps.changesets.outputs.publishedPackages }} })
