name: Release
on: create

jobs:
  build:
    if: github.ref_type == 'tag'
    uses: andrewiggins/publish-gh-release-package/.github/workflows/main.yml@main

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: npm-package
      - run: ls -al
      - name: Create draft release
        id: create-release
        uses: actions/github-script@v5
        with:
          # https://github.com/actions/github-script#run-a-separate-file-with-an-async-function
          script: |
            const script = require('./scripts/release/create.cjs')
            await script({ github, context })
      - name: Upload release artifact
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./scripts/release/upload.cjs')
            await script({ require, github, context, glob, ${{ steps.create-release.outputs.result }} })
