name: Release
on: create

jobs:
  build:
    if: github.ref_type == 'tag'
    uses: andrewiggins/publish-gh-release-package/.github/workflows/main.yml@main

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: npm-package
      - run: ls -al
